[tool.poetry]
name = "datamart-finviz"
version = "1.0.3"
description = "Finviz extension for DataMart"
authors = ["DataMart Team <hello@datamart.co>"]
readme = "README.md"
packages = [{ include = "datamart_finviz" }]

[tool.poetry.dependencies]
python = "^3.8"
datamart-core = "^1.1.5"
finvizfinance = "0.14.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."datamart_provider_extension"]
finviz = "datamart_finviz:finviz_provider"
