[tool.poetry]
name = "datamart-stockgrid"
version = "1.1.4"
description = "stockgrid extension for DataMart"
authors = ["DataMart Team <hello@datamart.co>"]
readme = "README.md"
packages = [{ include = "datamart_stockgrid" }]

[tool.poetry.dependencies]
python = "^3.8"
datamart-core = "^1.1.5"
pytest-freezegun = "^0.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."datamart_provider_extension"]
stockgrid = "datamart_stockgrid:stockgrid_provider"
