[tool.poetry]
name = "datamart-intrinio"
version = "1.1.4"
description = "Intrinio extension for DataMart"
authors = ["DataMart Team <hello@datamart.co>"]
readme = "README.md"
packages = [{ include = "datamart_intrinio" }]

[tool.poetry.dependencies]
python = "^3.8"
requests-cache = "^1.1.0"
datamart-core = "^1.1.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."datamart_provider_extension"]
intrinio = "datamart_intrinio:intrinio_provider"
